### ISSUE TITLE
image.layered - does it exist?

### ISSUE THREAD

**Issue by originalfoo** [aubergine10/Style#2]
Based on Helmod; https://github.com/Helfima/helmod/blob/master/prototypes/style.lua#L51

**Comment by Helfima** [comment]
I think it has not been implemented
i think is button type: sprite http://lua-api.factorio.com/latest/LuaGuiElement.html#LuaGuiElement.sprite

**Comment by originalfoo** [comment]
I've seen some mentions in forum a few weeks ago about layering sprites for GUI but still need to check. Will post topic link here if I can find it.

**Comment by originalfoo** [comment]
Layered images do exist, but not currently for GUI.
- [info from 0.11.0 release notes](https://github.com/aubergine10/Style/issues/27#issuecomment-247592074)
- [example `icons` property](https://github.com/aubergine10/Style/issues/26#issuecomment-247590994)

Closing this ticket as those  other tickets will deal with it.
