### ISSUE TITLE
Add: Sprite image

### ISSUE THREAD

**Issue by originalfoo** [aubergine10/Style#3]
Based on Helmod; https://github.com/Helfima/helmod/blob/master/prototypes/style.lua#L19

**Comment by Helfima** [comment]
i m not sure a type sprite existe perhaps i have try that

**Comment by originalfoo** [comment]
I'm sure I've seen something with a `type = 'sprite'` in some of the vanilla files, but maybe it was something to do with recipes or items instead of LuaGuiElement?

**Comment by Helfima** [comment]
waiting to see if someone asks you implementing

**Comment by originalfoo** [comment]
I just searched all files in the core and base mods and couldn't find one, so seems there isn't a `type = 'sprite'` image type.

**Comment by originalfoo** [comment]
Turns out there is a sprite image after all! See #33
